# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
$(FLOAT_OBJ): $(LIB_COMMON_DIR)/FLOAT.c
		@mkdir -p $(@D)
		@$(CC) -c  -o./obj/$(LIB_COMMON_DIR)/FLOAT.o $<

